name: Build Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        options:
          - production
          - staging
          - regtest
          - development
        required: true
        default: production
      submit:
        type: boolean
        default: true
        required: false

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint
    environment: ${{ inputs.profile || 'production' }}

  get_ios_build:
    name: Check existing iOS build
    type: get-build
    needs: [fingerprint]
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: ${{ inputs.profile || 'production' }}

  get_android_build:
    name: Check existing Android build
    type: get-build
    needs: [fingerprint]
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: ${{ inputs.profile || 'production' }}

  build_ios:
    name: Build iOS
    type: build
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    params:
      platform: ios
      profile: ${{ inputs.profile || 'production' }}

  build_android:
    name: Build Android
    type: build
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    params:
      platform: android
      profile: ${{ inputs.profile || 'production' }}

  submit_ios:
    name: Submit iOS Build
    type: submit
    needs: [get_ios_build, build_ios]
    if: ${{ (inputs.submit == true || inputs.submit == null) && (inputs.profile || 'production') != 'development' }}
    env:
      EXPO_DEBUG: '1'
    params:
      build_id: ${{ needs.build_ios.outputs.build_id || needs.get_ios_build.outputs.build_id }}
      profile: ${{ inputs.profile || 'production' }}

  submit_android:
    name: Submit Android Build
    type: submit
    needs: [get_android_build, build_android]
    if: ${{ (inputs.submit == true || inputs.submit == null) && (inputs.profile || 'production') != 'development' }}
    env:
      EXPO_DEBUG: '1'
    params:
      build_id: ${{ needs.build_android.outputs.build_id || needs.get_android_build.outputs.build_id }}
      profile: ${{ inputs.profile || 'production' }}
