name: Build Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        options:
          - production
          - staging
          - regtest
          - development
        required: true
        default: production
      submit:
        type: boolean
        default: true
        required: false

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint
    environment: ${{ inputs.profile || 'production' }}

  get-ios-build:
    name: Check existing iOS build
    type: get-build
    needs: [fingerprint]
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: ${{ inputs.profile || 'production' }}

  get-android-build:
    name: Check existing Android build
    type: get-build
    needs: [fingerprint]
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: ${{ inputs.profile || 'production' }}

  build-ios:
    name: Build iOS
    type: build
    needs: [get-ios-build]
    if: ${{ !needs.get-ios-build.outputs.build_id }}
    params:
      platform: ios
      profile: ${{ inputs.profile || 'production' }}

  build-android:
    name: Build Android
    type: build
    needs: [get-android-build]
    if: ${{ !needs.get-android-build.outputs.build_id }}
    params:
      platform: android
      profile: ${{ inputs.profile || 'production' }}

  submit-ios:
    name: Submit iOS Build
    type: submit
    needs: [get-ios-build, build-ios]
    if: ${{ (inputs.submit == true || inputs.submit == null) && (inputs.profile || 'production') != 'development' }}
    params:
      build_id: ${{ needs.build-ios.outputs.build_id || needs.get-ios-build.outputs.build_id }}
      profile: ${{ inputs.profile || 'production' }}

  submit-android:
    name: Submit Android Build
    type: submit
    needs: [get-android-build, build-android]
    if: ${{ (inputs.submit == true || inputs.submit == null) && (inputs.profile || 'production') != 'development' }}
    params:
      build_id: ${{ needs.build-android.outputs.build_id || needs.get-android-build.outputs.build_id }}
      profile: ${{ inputs.profile || 'production' }}
