import { Env } from '@env'

export const Config = {
  RELAYER_API_URL: Env.RELAYER_API_URL,

  RMO_CHAIN_ID: Env.RMO_CHAIN_ID,

  REGISTRATION_CONTRACT_ADDRESS: Env.REGISTRATION_CONTRACT_ADDRESS,
  STATE_KEEPER_CONTRACT_ADDRESS: Env.STATE_KEEPER_CONTRACT_ADDRESS,
  CERT_POSEIDON_SMT_CONTRACT_ADDRESS: Env.CERT_POSEIDON_SMT_CONTRACT_ADDRESS,
  REGISTRATION_POSEIDON_SMT_CONTRACT_ADDRESS: Env.REGISTRATION_POSEIDON_SMT_CONTRACT_ADDRESS,

  ICAO_COSMOS_GRPC: Env.ICAO_COSMOS_GRPC,
  MASTER_CERTIFICATES_BUCKETNAME: Env.MASTER_CERTIFICATES_BUCKETNAME,
  MASTER_CERTIFICATES_FILENAME: Env.MASTER_CERTIFICATES_FILENAME,

  POINTS_SVC_ID: Env.POINTS_SVC_ID,
}
